server:
  port: 8086
  servlet:
    context-path: /authorization

spring:
  profiles:
    active: dev
    
  redis:
    host: localhost
    port: 6379
    password: root

---
spring:
  profiles: dev
  
logging:
  level:
    com:
      emaster: info

---
spring:
  profiles: prod

logging:
  level:
    com:
      emaster: info