server:
  port: 8085

spring:
  profiles:
    active: dev

---
spring:
  profiles: dev
  data:
    mongodb:
      host: localhost
      port: 27017
      database: emaster
  
logging:
  level:
    com:
      emaster: debug
      
limitQuestionPerSession: 20
      
---
spring:
  profiles: prod

logging:
  level:
    com:
      emaster: info