server:
  port: 8080
  servlet:
    context-path: /portal

spring:
  profiles:
    active: dev

---
spring:
  profiles: dev
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.SecurityAutoConfiguration
  
logging:
  level:
    com:
      emaster: debug
security:
  oauth2:
    resource:
      user-info-uri: http://localhost:8086/authorization/user/info

---
spring:
  profiles: prod

logging:
  level:
    com:
      emaster: info