server:
  port: 8080

spring:
  profiles:
    active: dev

---
spring:
  profiles: dev
  
logging:
  level:
    com:
      emaster: debug
      
dataquery:
  baseUrl: http://localhost:8085/
---
spring:
  profiles: prod

logging:
  level:
    com:
      emaster: info