server:
  port: 8080
  servlet:
    context-path: /portal

spring:
  profiles:
    active: dev

---
spring:
  profiles: dev
  
dataquery:
  baseUrl: http://localhost:8085/dataquery
  
logging:
  level:
    com:
      emaster: debug

---
spring:
  profiles: prod

logging:
  level:
    com:
      emaster: info